// CAT ACTIONS
export const CREATE_CAT = "CREATE_CAT";
export const CREATE_CAT_SUCCESS = "CREATE_CAT_SUCCESS";
export const CREATE_CAT_FAILURE = "CREATE_CAT_FAILURE";
export const LOAD_CAT = "LOAD_CAT";
export const LOAD_CAT_SUCCESS = "LOAD_CAT_SUCCESS";
export const LOAD_CAT_FAILURE = "LOAD_CAT_FAILURE";
export const LOAD_CATS = "LOAD_CATS";
export const LOAD_CATS_SUCCESS = "LOAD_CATS_SUCCESS";
export const LOAD_CATS_NO_DATA_SUCCESS = "LOAD_CATS_NO_DATA_SUCCESS";
export const LOAD_CATS_FAILURE = "LOAD_CATS_FAILURE";
export const UPDATE_CAT = "UPDATE_CAT";
export const UPDATE_CAT_SUCCESS = "UPDATE_CAT_SUCCESS";
export const UPDATE_CAT_FAILURE = "UPDATE_CAT_FAILURE";
export const DELETE_CAT = "DELETE_CAT";
export const DELETE_CAT_SUCCESS = "DELETE_CAT_SUCCESS";
export const DELETE_CAT_FAILURE = "DELETE_CAT_FAILURE";

// DOG ACTIONS
export const CREATE_DOG = "CREATE_DOG";
export const CREATE_DOG_SUCCESS = "CREATE_DOG_SUCCESS";
export const CREATE_DOG_FAILURE = "CREATE_DOG_FAILURE";
export const LOAD_DOG = "LOAD_DOG";
export const LOAD_DOG_SUCCESS = "LOAD_DOG_SUCCESS";
export const LOAD_DOG_FAILURE = "LOAD_DOG_FAILURE";
export const LOAD_DOGS = "LOAD_DOGS";
export const LOAD_DOGS_SUCCESS = "LOAD_DOGS_SUCCESS";
export const LOAD_DOGS_NO_DATA_SUCCESS = "LOAD_DOGS_NO_DATA_SUCCESS";
export const LOAD_DOGS_FAILURE = "LOAD_DOGS_FAILURE";
export const UPDATE_DOG = "UPDATE_DOG";
export const UPDATE_DOG_SUCCESS = "UPDATE_DOG_SUCCESS";
export const UPDATE_DOG_FAILURE = "UPDATE_DOG_FAILURE";
export const DELETE_DOG = "DELETE_DOG";
export const DELETE_DOG_SUCCESS = "DELETE_DOG_SUCCESS";
export const DELETE_DOG_FAILURE = "DELETE_DOG_FAILURE";

// API STATUS ACTIONS
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";